export const TOUR_STORAGE_KEY = "linelens.final-tour-seen";
export const GUIDE_STORAGE_KEY = "linelens.page-guide-progress";

export type TourPage = "Dashboard" | "Machines" | "Quality" | "Incidents" | "Analytics";
export type Scenario = "bottleneck" | "quality";
export interface TourStep { id: string; page: TourPage; target: string; title: string; text: string; hint?: string; stationId?: string; scenario?: Scenario; dataView?: "observed" | "twin" | "forecast"; qualityFilter?: "REVIEW" | "WATCH" | "INSPECT" | "ALL"; validation?: boolean; }
export interface GuideChapter { id: string; label: string; page: TourPage; duration: string; summary: string; steps: readonly TourStep[]; }

const step = (id: string, page: TourPage, target: string, title: string, text: string, extra: Partial<TourStep> = {}): TourStep => ({ id, page, target, title, text, ...extra });

// One deliberate product story. Demo steps wait for the same backend simulation calls
// used by the visible Demo controls; this file never supplies operational values.
export const TOUR_STEPS: readonly TourStep[] = [
  step("welcome", "Dashboard", "factory-canvas", "Your digital factory", "Vehicles move through Body Shop, Paint Shop and Final Assembly. LineLens keeps an evolving view as the synthetic factory changes."),
  step("line", "Dashboard", "factory-canvas", "The production line", "This view shows the complete line and the vehicles moving between its three main sections."),
  step("choose", "Dashboard", "station-list", "Choose a station", "Select any station to see what is happening there now and where its evidence comes from."),
  step("station", "Dashboard", "station-inspector", "Understand a station", "The inspector compares the current cycle with normal behaviour, queue and confidence in one place.", { stationId: "FA-02", dataView: "twin" }),
  step("observed", "Dashboard", "forecast-control", "Observed", "Observed is information coming directly from the factory. This prototype labels synthetic telemetry clearly when it is the source.", { dataView: "observed" }),
  step("twin", "Dashboard", "forecast-control", "Twin", "Twin is LineLens’s best estimate of what is happening now when evidence is incomplete.", { dataView: "twin" }),
  step("forecast", "Dashboard", "forecast-control", "Forecast", "Forecast shows what LineLens expects may happen next if nothing changes.", { dataView: "forecast" }),
  step("gap", "Dashboard", "station-inspector", "Sensor gaps", "Not every station has modern sensors. At a basic-data station, LineLens combines the data that exists and shows lower confidence.", { stationId: "FA-01", dataView: "twin" }),
  step("explore", "Dashboard", "viewport-controls", "Explore the factory", "Use Orbit to inspect the line, Walk for first-person exploration, and Flythrough for an automatic view of the production line."),
  step("bottleneck", "Dashboard", "station-inspector", "Developing bottleneck", "LineLens is now running the real Bottleneck demonstration. It waits for the simulator and prediction pipeline before showing a warning.", { stationId: "FA-02", scenario: "bottleneck", dataView: "twin" }),
  step("why", "Dashboard", "station-inspector", "Why it was flagged", "A warning is based on a persistent pattern: current cycle, normal cycle, difference and queue—not one random slow cycle.", { stationId: "FA-02", dataView: "twin" }),
  step("impact", "Dashboard", "forecast-impact", "What may happen next", "The computed no-intervention forecast shows potential queue growth and downstream starvation using the live simulator output.", { stationId: "FA-02", dataView: "forecast" }),
  step("incident", "Incidents", "incident-list", "From warning to incident", "Important predictions become Incidents so the plant team has one focused place to investigate."),
  step("checks", "Incidents", "incident-response", "What to check", "The incident explains what happened, what may happen next, why it was detected and what the team can check. People decide what to do."),
  step("quality", "Quality", "quality-vehicle-list", "Vehicle quality", "LineLens now runs the real Weld quality demonstration. Production problems are not only about speed; every vehicle also has a quality history.", { scenario: "quality", qualityFilter: "ALL" }),
  step("record", "Quality", "digital-build-record", "Digital build record", "For one vehicle, LineLens keeps the stations, tools, batches and meaningful process evidence that shaped its build.", { qualityFilter: "ALL" }),
  step("early", "Quality", "quality-primary", "Early quality warning", "A vehicle can be flagged before normal End-of-Line confirmation when earlier process evidence looks unusual. The warning includes risk, likely origin and next check.", { qualityFilter: "INSPECT" }),
  step("pattern", "Quality", "common-pattern", "Common pattern", "When several risky vehicles share a real tool, cell or lot from the Quality pipeline, LineLens highlights the pattern. It is a lead to investigate, not a confirmed root cause.", { qualityFilter: "INSPECT" }),
  step("stations", "Machines", "station-directory", "See the bigger picture", "Stations compares the whole line. Trends then shows how one station’s behaviour changes over time."),
  step("trust", "Analytics", "validation-summary", "Trust and finish", "Predictions are checked against later simulated outcomes. Wrong predictions are not hidden. You now know the LineLens story: see now, predict next, trace affected vehicles and respond with evidence.", { validation: true }),
] as const;

export const GUIDE_CHAPTERS: readonly GuideChapter[] = [
  {
    id: "dashboard", label: "Dashboard", page: "Dashboard", duration: "~3 min", summary: "Read the factory, inspect a station, and understand early warning.", steps: [
      step("factory", "Dashboard", "factory-canvas", "Start with the whole factory", "This is the live digital view of the 11-station line. Vehicles move through Body Shop, Paint Shop, and Final Assembly while LineLens keeps the view updated from synthetic factory telemetry.", { hint: "Start here when you need a fast sense of where production is flowing." }),
      step("list", "Dashboard", "station-list", "Choose the place to investigate", "The station list is the quickest way to move from the line view to a specific process. Each row shows the current operating state and an estimated cycle time, so you can find a station that deserves attention.", { hint: "Select a station name; its inspector opens on the right without leaving the Dashboard." }),
      step("status", "Dashboard", "station-inspector", "Read the selected station", "The inspector puts the essentials together: current vehicle, current cycle, normal cycle, difference from normal, queue, and confidence. A difference that stays positive and grows is more meaningful than one slow cycle.", { hint: "Read current cycle beside normal cycle before deciding whether a change matters." }),
      step("confidence", "Dashboard", "station-inspector", "Understand the evidence", "Confidence explains how strong the available evidence is. Direct data means a fresh station measurement is available; limited or basic data means the Twin is using the best evidence it has and tells you so.", { hint: "Use confidence to judge how closely to investigate, not as a quality score for the factory." }),
      step("views", "Dashboard", "forecast-control", "Compare Observed, Twin, and Forecast", "Observed shows direct factory signals. Twin shows LineLens’s current best estimate. Forecast shows the simulator’s computed no-intervention view of what may happen next.", { hint: "Switch to Forecast only after understanding the current Twin; it answers “what could happen if nothing changes?”" }),
      step("controls", "Dashboard", "viewport-controls", "Explore without losing context", "The viewport toolbar holds camera controls, Walk Mode, Factory Flythrough, simulation controls, and synthetic Demo scenarios. These controls affect only the local prototype simulation, never equipment.", { hint: "Use Walk for a first-person aisle view and Flythrough for a quick automatic overview." }),
      step("warning", "Dashboard", "station-inspector", "Know what becomes an incident", "When LineLens detects a persistent risk, the inspector explains why using the cycle, normal behaviour, queue, and evidence. Important warnings are then grouped into Incidents so the team can investigate in one place.", { hint: "A healthy screen is expected. Use a synthetic Demo scenario only when you want to demonstrate a real warning pipeline." }),
    ],
  },
  {
    id: "quality", label: "Quality", page: "Quality", duration: "~3 min", summary: "Prioritise vehicle review, trace build history, and interpret patterns carefully.", steps: [
      step("vehicles", "Quality", "quality-vehicle-list", "Begin with vehicles that need attention", "The left panel prioritises vehicles whose quality evidence warrants review. If it says the line is calm, that is a real result: no vehicle currently crosses the watch threshold.", { hint: "Use All Vehicles when you need the full monitored population, not only the prioritised list." }),
      step("filters", "Quality", "quality-vehicle-list", "Use Watch and Inspect correctly", "Watch means the vehicle has evidence worth following. Inspect means the risk is higher and the prototype recommends an earlier check. These labels help prioritise work; they are not confirmed defects.", { hint: "Open Inspect first when time is limited, then use Watch to monitor the next tier." }),
      step("risk", "Quality", "quality-primary", "Read the vehicle decision card", "The main card identifies the vehicle, its current location, and its current Quality Risk. Risk is the chance that the vehicle may need extra inspection based on the process evidence collected so far.", { hint: "Treat the percentage as an inspection priority, not a verdict that the vehicle has failed." }),
      step("reason", "Quality", "quality-primary", "Ask why, where, and what next", "Why? explains the unusual process evidence. Likely origin identifies the upstream station to investigate. What to do gives an inspection action and location while clearly keeping the plant team in control.", { hint: "A likely origin is a lead for investigation—it is not automatically a confirmed root cause." }),
      step("record", "Quality", "digital-build-record", "Trace the Digital Build Record", "Build History follows the selected vehicle through the stations it has completed. Open Build details to see the relevant station, equipment, and retained process evidence for that specific vehicle.", { hint: "Use this record when an engineer asks “what happened to this vehicle before we saw the risk?”" }),
      step("pattern", "Quality", "common-pattern", "Interpret Common Pattern safely", "This panel compares the risky cohort and highlights a tool, cell, or lot shared more often than expected. It narrows the search area, but does not prove that the shared factor caused the issue.", { hint: "Use the pattern to choose where to inspect first, then confirm findings with normal engineering checks." }),
      step("validation", "Quality", "quality-validation", "Check whether warnings were useful", "LineLens records completed simulated outcomes as vehicles reach inspection. Warnings checked, correct warnings, and time gained are shown only when actual simulated outcomes exist; otherwise the product says so plainly.", { hint: "Open technical metrics only when you need supporting detail—not to make an operational decision." }),
    ],
  },
  {
    id: "incidents", label: "Incidents", page: "Incidents", duration: "~3 min", summary: "Turn an important prediction into an evidence-led, human response.", steps: [
      step("attention", "Incidents", "incident-list", "Understand the attention list", "Incidents are the short list of predictions that need a human response. The Active tab shows current work; Resolved keeps a transparent history for the current simulation session.", { hint: "No active incidents means the factory is operating within expected conditions—it is not an empty or broken page." }),
      step("select", "Incidents", "incident-list", "Open one incident at a time", "Select an item to focus the page on one problem. The title, source, detection time, and status make it easy to orient yourself before reading the supporting evidence.", { hint: "If there is no active incident, use a synthetic Demo scenario to see the complete workflow with real backend output." }),
      step("happened", "Incidents", "incident-response", "Read the problem before the detail", "What happened summarises the observed change. What may happen next describes the predicted operational impact if the condition continues. These statements are separated so current evidence is not confused with a forecast.", { hint: "Start here during a handover: it gives the next person the situation in plain language." }),
      step("evidence", "Incidents", "incident-response", "See why LineLens raised it", "The evidence section shows the measured or estimated signals behind the warning. It explains the model’s reasoning without asking the operator to interpret raw model internals.", { hint: "Look for a persistent difference, queue effect, or shared quality evidence—not a single isolated signal." }),
      step("checks", "Incidents", "incident-response", "Turn evidence into checks", "Recommended checks identify the practical places to inspect: station condition, tooling, vehicle cohort, or process evidence. They are guidance for the team, never automatic factory actions.", { hint: "Use the checks as a starting point and document the engineering finding in the response note." }),
      step("workflow", "Incidents", "incident-response-panel", "Track the human response", "Acknowledge, Start investigation, Mark check complete, Add note, and Resolve record the response lifecycle. They make ownership visible without sending commands to machines or PLCs.", { hint: "Resolve only after the team has completed its real-world checks; LineLens does not resolve an incident automatically." }),
    ],
  },
  {
    id: "stations", label: "Stations", page: "Machines", duration: "~2 min", summary: "Compare every station using the same operational language.", steps: [
      step("directory", "Machines", "station-directory", "Use the line-wide station directory", "Stations puts the whole line in one comparable table. It is useful when you want to move beyond the currently selected station and see which process is behaving differently.", { hint: "Click a row to take that station back to the Dashboard inspector." }),
      step("source", "Machines", "station-directory", "Start with the data source", "Source tells you whether the view is using direct, partial, or basic factory signals. This makes uneven sensor coverage visible instead of hiding it behind one uniform number.", { hint: "A basic-data station can still be useful to monitor, but its confidence should guide how strongly you act on it." }),
      step("compare", "Machines", "station-directory", "Compare current behaviour with normal", "Factory data is the direct measurement when available. Twin is the current estimate. Normal is the learned healthy cycle, and Difference shows how far the station is from that baseline.", { hint: "Sort your attention mentally by a sustained Difference together with confidence—not by one column alone." }),
      step("confidence", "Machines", "station-directory", "Use confidence as context", "Confidence reflects the strength and freshness of available evidence. It helps explain why one station’s estimate is more certain than another without pretending the factory has equal instrumentation everywhere.", { hint: "Open the station on Dashboard when you need the evidence behind a row." }),
      step("action", "Machines", "station-directory", "Move from comparison to action", "The table is a comparison surface, not an alarm wall. If a station looks unusual, select it, inspect the details on Dashboard, and use Incidents only when a real warning has been raised.", { hint: "This keeps normal line scanning calm and saves the detailed workflow for genuine risks." }),
    ],
  },
  {
    id: "trends", label: "Trends", page: "Analytics", duration: "~3 min", summary: "See how a station is changing over time without mistaking one point for a trend.", steps: [
      step("purpose", "Analytics", "trends-page", "What Trends is for", "Trends helps you understand how one station has changed over time. It is for investigating a developing pattern, not for reading a single live status number.", { hint: "Choose a station with a meaningful question—for example, “is the cycle drifting away from normal?”" }),
      step("selector", "Analytics", "trends-page", "Choose the station you want to compare", "Use the Station selector in the page header to change the process shown in every chart below. The same selection keeps the comparison consistent across the workspace.", { hint: "Start with a station that is highlighted on Dashboard or appears unusual in Stations." }),
      step("cycle", "Analytics", "twin-cycle-chart", "Read the cycle-time chart", "This chart separates direct factory data, the Twin estimate, and normal behaviour. The separation matters: it shows what was measured, what LineLens inferred, and what healthy operation usually looks like.", { hint: "Look for several adjacent points moving away from normal, not one isolated spike." }),
      step("difference", "Analytics", "difference-chart", "Focus on the difference from normal", "This chart makes the gap between the Twin and normal behaviour easier to see. A difference that persists or grows is a stronger early-warning signal than a short fluctuation that returns to normal.", { hint: "Use this chart to explain why a slowdown is developing before it becomes an obvious queue." }),
      step("risk", "Analytics", "risk-chart", "Understand bottleneck risk", "Bottleneck risk combines persistent deviation and flow signals. It is an interpretable decision-support signal, not a raw machine alarm and not an instruction to stop the line.", { hint: "Open the Dashboard forecast or an Incident when you need the expected operational impact and recommended checks." }),
      step("decision", "Analytics", "trends-page", "Use Trends in the right order", "First identify an unusual station, then compare its cycle and difference from normal, then check the forecast or Incident for impact and next checks. This sequence keeps the charts connected to a practical decision.", { hint: "If the charts look calm, no action is needed—continue monitoring instead of searching for a problem." }),
    ],
  },
] as const;

export interface TourProgress { step: number; complete: boolean; }
export const newTour = (): TourProgress => ({ step: 0, complete: false });
export const nextTourStep = (p: TourProgress): TourProgress => p.step >= TOUR_STEPS.length - 1 ? { step: p.step, complete: true } : { step: p.step + 1, complete: false };
export const previousTourStep = (p: TourProgress): TourProgress => ({ step: Math.max(0, p.step - 1), complete: false });
export const hasSeenTour = (s: Pick<Storage, "getItem">) => s.getItem(TOUR_STORAGE_KEY) === "1";
export const rememberTour = (s: Pick<Storage, "setItem">) => s.setItem(TOUR_STORAGE_KEY, "1");
export const completedGuides = (s: Pick<Storage, "getItem">): string[] => { try { return JSON.parse(s.getItem(GUIDE_STORAGE_KEY) ?? "[]"); } catch { return []; } };
export const rememberGuide = (s: Pick<Storage, "getItem" | "setItem">, id: string) => { const next = [...new Set([...completedGuides(s), id])]; s.setItem(GUIDE_STORAGE_KEY, JSON.stringify(next)); return next; };
